apiVersion: kamaji.clastix.io/v1alpha1
kind: DataStore
metadata:
  name: nats-bronze
spec:
  driver: nats
  endpoints:
    - bronze-nats.nats-system.svc:4222
  basicAuth:
    username:
      content: YWRtaW4=
    password:
      secretReference:
        name: nats-bronze-config
        namespace: nats-system
        keyPath: password
  tlsConfig:
    certificateAuthority:
      certificate:
        secretReference:
          name: nats-bronze-config
          namespace: nats-system
          keyPath: ca.crt
    clientCertificate:
      certificate:
        secretReference:
          name: nats-bronze-config
          namespace: nats-system
          keyPath: server.crt
      privateKey:
        secretReference:
          name: nats-bronze-config
          namespace: nats-system
          keyPath: server.key
